// <auto-generated />
namespace GIS_visualization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class date_Change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(date_Change));
        
        string IMigrationMetadata.Id
        {
            get { return "201706130931163_date_Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
